### ISSUE TITLE
perf compare

### ISSUE THREAD

**Issue by futurist** [bredele/domwalk#2]
How about the perf compared with:

```js
[root].concat([].slice.apply(root.querySelectorAll('*'))).forEach(cb)
```

the result is same

**Comment by bredele** [comment]
@futurist interesting! Performance aside (I didn’t test it yet) this piece of code is way more concise and smarter!

**Comment by bredele** [comment]
@futurist from what I see, the recursive version is a bit faster. However, because it's recursive, you could reach a maximum stack size depending on the number of nodes.

**Comment by futurist** [comment]
I think the lib could add a feature that `skip` some nodes, like `return false` of `cb` to skip the node and it's children, that way the loop have more sense to use.

**Comment by bredele** [comment]
Do you have any concrete example to help me understand?

**Comment by futurist** [comment]
Like you have a `table`, and want to skip second `tr`, like below:

```js
walk(table, node=>isSecondTr(node) ? false : true)
```

That way the whole 2nd `tr` skipped, and less looper.

**Comment by bredele** [comment]
@futurist I think you could do that quite easily by decorating domwalk.

**Comment by futurist** [comment]
you are right, I''ve already done that! This lib is a good start point to doing things!
